use_frameworks!

target 'Seam3_Example' do

  platform :ios, '10.0'
	
  pod 'Seam3', :path => '../'

  target 'Seam3_Tests' do
    inherit! :search_paths
  end
end

target 'Seam3_Example_OSX' do
  platform :osx, '10.12'
  pod 'Seam3', :path => '../'
end


target 'Seam3_Example_TVOS' do
  platform :tvos, '10.0'
  pod 'Seam3', :path => '../'
end
