use_frameworks!

target 'Seam3_Example' do
  pod 'Seam3', :path => '../'

  target 'Seam3_Tests' do
    inherit! :search_paths
  end
end

target 'Seam3_Example_OSX' do
  pod 'Seam3', :path => '../'
end


target 'Seam3_Example_TVOS' do
  pod 'Seam3', :path => '../'
end
